#' Interactive epicurve via plotly with sensible defaults
#'
#' Thin wrapper around [plotly::ggplotly()] that fixes the rough edges
#' you get when converting an epicurve plot:
#'
#' * Uses the `text` aesthetic (auto-generated by [geom_epicurve()]) as
#'   the sole tooltip source.
#' * Strips the default `"trace 0"`, `"trace 1"`, ... suffix from hover
#'   labels so tooltips show only the case/period information.
#' * Re-injects the ggplot `subtitle` into the plotly title (plotly
#'   silently drops `subtitle`).
#' * For [geom_epicurve()] symbol mode, the ggplot legend keys are drawn
#'   with the actual Unicode symbol; plotly cannot honour that custom
#'   `draw_key`, so the legend is suppressed by default and the symbol
#'   meaning is communicated via the hover tooltip instead. Pass
#'   `keep_symbol_legend = TRUE` to keep plotly's default (ambiguous)
#'   `"Aa"` legend.
#'
#' @param p A ggplot built with [geom_epicurve()].
#' @param tooltip Passed to [plotly::ggplotly()]; defaults to `"text"`
#'   which uses the auto-generated tooltip.
#' @param keep_symbol_legend If `FALSE` (the default), hide the legend
#'   for layers that use a custom symbol because plotly renders those
#'   keys as `"Aa"`.
#' @param ... Further arguments passed to [plotly::ggplotly()].
#'
#' @return A plotly htmlwidget.
#'
#' @examples
#' \dontrun{
#' library(ggplot2)
#' cases <- simulate_outbreak(n = 30, prop_missing = 0)
#' p <- ggplot(cases, aes(x = onset_date)) +
#'   geom_epicurve(fill = "steelblue") +
#'   scale_y_epicurve() +
#'   theme_minimal()
#' epicurve_ggplotly(p)
#' }
#'
#' @export
epicurve_ggplotly <- function(p, tooltip = "text",
                              keep_symbol_legend = FALSE, ...) {
  if (!requireNamespace("plotly", quietly = TRUE)) {
    stop("epicurve_ggplotly() requires the 'plotly' package. ",
         "Install with install.packages('plotly').", call. = FALSE)
  }
  if (!inherits(p, "ggplot")) {
    stop("`p` must be a ggplot object.", call. = FALSE)
  }

  # Detect whether any layer uses a custom symbol so we can suppress the
  # uninformative "Aa" legend that plotly produces for text layers.
  has_symbol <- FALSE
  for (layer in p$layers) {
    if (!is.null(layer$stat_params$symbol) ||
        !is.null(layer$geom_params$symbol)) {
      has_symbol <- TRUE
      break
    }
  }
  if (has_symbol && isFALSE(keep_symbol_legend)) {
    p <- p + ggplot2::theme(legend.position = "none")
  }

  pl <- plotly::ggplotly(p, tooltip = tooltip, ...)

  # Strip plotly's default "(trace 0)" / "(trace 1)" suffix from hovers.
  # `<extra></extra>` removes the right-hand side trace label.
  pl <- plotly::style(pl, hovertemplate = "%{text}<extra></extra>")

  # Re-inject the ggplot subtitle, which ggplotly() drops.
  sub <- p$labels$subtitle
  if (!is.null(sub) && nzchar(sub)) {
    title <- p$labels$title
    pl <- plotly::layout(pl, title = list(
      text = paste0(title %||% "",
                    "<br><sup>", sub, "</sup>")
    ))
  }

  pl
}
