#' Interactive epicurve via plotly with sensible defaults
#'
#' Thin wrapper around [plotly::ggplotly()] that fixes the rough edges
#' you get when converting an epicurve plot:
#'
#' * Uses the `text` aesthetic (auto-generated by [geom_epicurve()]) as
#'   the sole tooltip source.
#' * Sets a per-trace hovertemplate so the default `"trace 0"`,
#'   `"trace 1"`, ... suffix never appears, and silences hover entirely
#'   for traces that carry no useful tooltip (the geom_segment used by
#'   `annotate_event()`, for example).
#' * Re-injects the ggplot `subtitle` into the plotly title (plotly
#'   silently drops `subtitle`).
#' * Swaps the auto-added [coord_epicurve()] for `coord_cartesian()`
#'   before conversion (plotly does not honour custom coords) and
#'   instead applies the equivalent aspect by setting the widget
#'   height, so hourly / sub-daily plots get the same shorter panel
#'   they get in static ggplot2 output.
#' * For [geom_epicurve()] symbol mode, plotly cannot render the custom
#'   `draw_key` so the default legend swatch is the unhelpful `"Aa"`
#'   glyph. The wrapper hides plotly's auto-legend and replaces it
#'   with a small annotation block in the top-right of the panel that
#'   lists each `symbol category` mapping so the symbol-to-category
#'   meaning is preserved.
#'
#' @param p A ggplot built with [geom_epicurve()].
#' @param tooltip Passed to [plotly::ggplotly()]; defaults to `"text"`
#'   which uses the auto-generated tooltip.
#' @param keep_symbol_legend If `FALSE` (the default), replace
#'   plotly's auto-generated legend for symbol layers with a custom
#'   annotation legend that shows the actual symbols (the auto legend
#'   would render keys as the placeholder `"Aa"` glyph). Set to
#'   `TRUE` to keep plotly's default behaviour.
#' @param width,height Optional widget dimensions in pixels. When
#'   `height` is `NULL` (the default) the wrapper picks a height that
#'   matches the static-plot aspect for datetime axes; for date /
#'   numeric axes the htmlwidgets default is left alone.
#' @param ... Further arguments passed to [plotly::ggplotly()].
#'
#' @return A plotly htmlwidget.
#'
#' @examples
#' \dontrun{
#' library(ggplot2)
#' cases <- simulate_outbreak(n = 30, prop_missing = 0)
#' p <- ggplot(cases, aes(x = onset_date)) +
#'   geom_epicurve(fill = "steelblue") +
#'   scale_y_epicurve() +
#'   theme_minimal()
#' epicurve_ggplotly(p)
#' }
#'
#' @export
epicurve_ggplotly <- function(p, tooltip = "text",
                              keep_symbol_legend = FALSE,
                              width = NULL, height = NULL, ...) {
  if (!requireNamespace("plotly", quietly = TRUE)) {
    stop("epicurve_ggplotly() requires the 'plotly' package. ",
         "Install with install.packages('plotly').", call. = FALSE)
  }
  if (!inherits(p, "ggplot")) {
    stop("`p` must be a ggplot object.", call. = FALSE)
  }

  # ---- 1. Symbol-mode detection (for the legend replacement below) ----
  symbol_specs <- list()  # list of list(symbol_vec, group_col, palette)
  for (layer in p$layers) {
    sym <- layer$stat_params$symbol %||% layer$geom_params$symbol
    if (!is.null(sym) && length(sym) > 1 && !is.null(names(sym))) {
      symbol_specs[[length(symbol_specs) + 1]] <- list(symbol = sym)
    }
  }
  has_symbol <- length(symbol_specs) > 0

  # ---- 2. Compute datetime aspect for a sensible widget height ------
  auto_height <- NULL
  if (is.null(height) && inherits(p$coordinates, "CoordEpicurve")) {
    auto_height <- tryCatch({
      b <- suppressMessages(suppressWarnings(ggplot2::ggplot_build(p)))
      xr <- b$layout$panel_scales_x[[1]]$dimension()
      yr <- b$layout$panel_scales_y[[1]]$dimension()
      xr_num <- as.numeric(xr); yr_num <- as.numeric(yr)
      # Only kick in for datetime x (POSIXct seconds-since-epoch magnitude)
      if (length(xr_num) == 2 && xr_num[1] > 1e7) {
        ratio <- max(0.15, min(2, 3600 * diff(yr_num) / diff(xr_num)))
        # Assume default plotly widget width ~700 px; padding ~150 px
        plot_w <- if (is.null(width)) 700 else width
        round(plot_w * ratio + 150)
      } else NULL
    }, error = function(e) NULL)
  }

  # ---- 3. Swap CoordEpicurve for coord_cartesian() ------------------
  # plotly cannot use a custom Coord; it falls back unpredictably.
  if (inherits(p$coordinates, "CoordEpicurve")) {
    p$coordinates <- ggplot2::coord_cartesian()
  }

  # ---- 4. Symbol legend: hide plotly auto-legend, add annotation ----
  if (has_symbol && isFALSE(keep_symbol_legend)) {
    p <- p + ggplot2::theme(legend.position = "none")
  }

  pl <- plotly::ggplotly(p, tooltip = tooltip, ...)

  # Each stacked case is its own bar; without overlay mode plotly would
  # try to group bars side-by-side or stack-add them and the visual
  # layout would no longer match the static ggplot.
  pl <- plotly::layout(pl, barmode = "overlay", bargap = 0)

  # ---- 5. Per-trace hovertemplate: only where text is meaningful ----
  pl <- .epicurve_fix_hover(pl)

  # ---- 6. Re-inject subtitle (ggplotly drops it) --------------------
  sub <- p$labels$subtitle
  if (!is.null(sub) && nzchar(sub)) {
    title <- p$labels$title
    pl <- plotly::layout(pl, title = list(
      text = paste0(title %||% "",
                    "<br><sup>", sub, "</sup>")
    ))
  }

  # ---- 7. Custom symbol-legend annotation ---------------------------
  if (has_symbol && isFALSE(keep_symbol_legend)) {
    legend_lines <- character(0)
    for (spec in symbol_specs) {
      sv <- spec$symbol
      for (cat in names(sv)) {
        legend_lines <- c(legend_lines, paste0(sv[[cat]], "  ", cat))
      }
    }
    if (length(legend_lines) > 0) {
      pl <- plotly::layout(pl,
        annotations = list(list(
          x = 1, y = 1, xref = "paper", yref = "paper",
          xanchor = "right", yanchor = "top",
          text = paste(legend_lines, collapse = "<br>"),
          showarrow = FALSE,
          align = "left",
          bgcolor = "rgba(255,255,255,0.85)",
          bordercolor = "grey70", borderwidth = 1, borderpad = 4,
          font = list(size = 12)
        ))
      )
    }
  }

  # ---- 8. Apply auto height for datetime --------------------------
  if (!is.null(width))  pl$width  <- width
  if (!is.null(height)) {
    pl$height <- height
  } else if (!is.null(auto_height)) {
    pl$height <- auto_height
  }

  pl
}

# Per-trace hover handler. Sets `hovertemplate = "%{text}<extra></extra>"`
# on every trace whose `text` is a non-empty character vector that is
# something other than the empty string. Traces without useful text get
# `hoverinfo = "skip"` so the user never sees `%{text}` rendered
# literally (which is what plotly does when the template references a
# missing field) or the placeholder `"trace 0"` label.
.epicurve_fix_hover <- function(pl) {
  build <- plotly::plotly_build(pl)
  for (i in seq_along(build$x$data)) {
    tr <- build$x$data[[i]]
    txt <- tr$text
    has_text <- !is.null(txt) && length(txt) > 0 &&
      any(!is.na(txt) & nzchar(as.character(txt)))
    if (has_text) {
      build$x$data[[i]]$hovertemplate <- "%{text}<extra></extra>"
      build$x$data[[i]]$hoverinfo <- "text"
    } else {
      build$x$data[[i]]$hoverinfo <- "skip"
      build$x$data[[i]]$hovertemplate <- NULL
    }
  }
  build
}
